### ISSUE TITLE
bug: create_db and super_user not work for tf rwc provider

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/terraform-provider-risingwavecloud#31]
Create a rwc user via terraform with the below definition

```
resource "risingwavecloud_cluster_user" "cy-gcp-1-user-super_user" {
  cluster_id = "xxxx"
  username   = "cy-gcp-super_user"
  password   = ""
  create_db  = true
  super_user = true
}
```
Got the following error
![image](https://github.com/risingwavelabs/terraform-provider-risingwavecloud/assets/35356271/81fdf13c-0400-4759-a53f-3367707b1793)

**Comment by mikechesterwang** [comment]
close as it is an internal issue in the cloud.
